# Generated by Django 5.0.1 on 2024-02-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_follow_followed_alter_follow_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followed',
            new_name='follow_back',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follow', 'follow_back')},
        ),
    ]
