# Generated by Django 5.0.1 on 2024-02-12 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_follow_unique_together_follow_youser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='youser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
