# Generated by Django 5.0.1 on 2024-02-01 17:44

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblogmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createblogmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
        migrations.AddField(
            model_name='createblogmodel',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='createblogmodel',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('public', 'PUBLIC')], default='draft', max_length=255),
        ),
        migrations.AlterField(
            model_name='createblogmodel',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
