# Generated by Django 5.0.1 on 2024-01-30 11:13

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblogmodel',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
