# Generated by Django 5.0.1 on 2024-02-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcommentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommentmodel',
            name='comment',
            field=models.TextField(),
        ),
    ]
