# Generated by Django 5.0.1 on 2024-02-03 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogcommentmodel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcommentmodel',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.blogcommentmodel'),
        ),
    ]
