# Generated by Django 5.0.1 on 2024-02-05 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogcommentmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcommentmodel',
            options={'ordering': ['-modified_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='createblogmodel',
            options={'ordering': ['-modified_at', '-created_at']},
        ),
    ]
